/********************************************************************************
** Form generated from reading UI file 'Antonov.ui'
**
** Created by: Qt User Interface Compiler version 6.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ANTONOV_H
#define UI_ANTONOV_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCommandLinkButton>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_AntonovClass
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page_3;
    QFrame *frame_5;
    QLabel *label_2;
    QFrame *frame_6;
    QFrame *frame_11;
    QFrame *frame_22;
    QPushButton *button_back;
    QFrame *frame_23;
    QPushButton *button_startkadr;
    QFrame *frame_24;
    QPushButton *button_nulllll;
    QFrame *frame_25;
    QPushButton *button_smesh;
    QFrame *frame_26;
    QPushButton *button_null3;
    QFrame *frame_27;
    QPushButton *button_null2;
    QFrame *frame_28;
    QPushButton *button_null100;
    QFrame *frame_29;
    QPushButton *button_selectprog;
    QFrame *frame_8;
    QFrame *frame_10;
    QProgressBar *progressBar_runtime;
    QLabel *label_time;
    QLabel *label_date;
    QFrame *frame_15;
    QPushButton *button_numeration;
    QFrame *frame_16;
    QPushButton *button_smenaekrana;
    QFrame *frame_17;
    QPushButton *button_mmdyum;
    QFrame *frame_18;
    QPushButton *button_changesk;
    QFrame *frame_19;
    QPushButton *button_priv;
    QFrame *frame_20;
    QPushButton *button_null4;
    QFrame *frame_21;
    QPushButton *button_privyazka;
    QFrame *frame_7;
    QLabel *label_chanel;
    QLabel *label_sostoyanine;
    QLabel *label_rejim_isp;
    QDockWidget *dockWidget;
    QWidget *dockWidgetContents;
    QLabel *label_sksskd;
    QLabel *label_z_value_current;
    QLineEdit *label_z_axis;
    QLineEdit *lineEdit_4;
    QLabel *label_y_value_current;
    QLineEdit *lineEdit_3;
    QLabel *label_y_value_final;
    QLabel *label_x_value_final;
    QLabel *label_z_value_final;
    QLineEdit *label_y_axis;
    QFrame *frame_3;
    QLabel *label_x_value_current;
    QLineEdit *label_x_axis;
    QDockWidget *dockWidget_2;
    QWidget *dockWidgetContents_2;
    QStackedWidget *stackedWidget_winchan;
    QWidget *page;
    QTextEdit *textEdit;
    QLabel *label_t_code_3;
    QLabel *label_g_code_20;
    QLabel *label_g_code_8;
    QLabel *label_d_code_4;
    QLabel *label_d_code_3;
    QLabel *label_g_code_13;
    QLabel *label_g_code_11;
    QLabel *label_g_code_27;
    QLabel *label_d_code;
    QLabel *label_m_code_4;
    QLabel *label_m_code_6;
    QLabel *label_g_code_10;
    QLabel *label_g_code_7;
    QLabel *label_g_code_16;
    QLabel *label_g_code_12;
    QLabel *label_g_code_26;
    QLabel *label_m_code_2;
    QLabel *label_g_code_6;
    QLabel *label_t_code_2;
    QLabel *label_g_code_21;
    QLabel *label_g_code_2;
    QLabel *label_m_code_5;
    QLabel *label_g_code_9;
    QLabel *label_g_code;
    QLabel *label_m_code;
    QLabel *label_m_code_3;
    QLabel *label_g_code_3;
    QLabel *label_g_code_15;
    QLabel *label_g_code_14;
    QLabel *label_g_code_22;
    QLabel *label_m_code_1;
    QLabel *label_g_code_23;
    QLabel *label_g_code_19;
    QLabel *label_d_code_2;
    QLabel *label_g_code_17;
    QLabel *label_g_code_4;
    QLabel *label_t_code_1;
    QLabel *label_g_code_24;
    QLabel *label_g_code_1;
    QLabel *label_g_code_29;
    QLabel *label_t_code;
    QLabel *label_g_code_25;
    QLabel *label_d_code_1;
    QLabel *label_t_code_6;
    QLabel *label_g_code_28;
    QLabel *label_t_code_4;
    QLabel *label_g_code_5;
    QLabel *label_g_code_18;
    QLabel *label_t_code_5;
    QWidget *page_2;
    QGraphicsView *graphView_simul;
    QDockWidget *dockWidget_3;
    QWidget *dockWidgetContents_3;
    QCommandLinkButton *commandLinkButton_start;
    QCommandLinkButton *commandLinkButton_reset;
    QCommandLinkButton *commandLinkButton_resetalarms;
    QCommandLinkButton *commandLinkButton_stop;
    QDockWidget *dockWidget_4;
    QWidget *dockWidgetContents_4;
    QLabel *info_line;
    QDockWidget *dockWidget_5;
    QWidget *dockWidgetContents_5;
    QLabel *label_language;
    QDockWidget *dockWidget_6;
    QWidget *dockWidgetContents_6;
    QLineEdit *label_feed_rate;
    QSlider *slider_feed_rate;
    QLineEdit *label_spindle_speed;
    QLabel *label_feed_value;
    QSlider *slider_spindle_speed;
    QLabel *label_changessk;
    QLabel *label_spindle_value;
    QDockWidget *dockWidget_7;
    QWidget *dockWidgetContents_7;
    QListWidget *listWidget_program;
    QDockWidget *dockWidget_8;
    QWidget *dockWidgetContents_8;
    QLabel *label_error;
    QWidget *page_4;
    QFrame *frame_14;
    QLabel *label_chanel_4;
    QLabel *label_sostoyanine_4;
    QLabel *label_rejim_isp_4;
    QFrame *frame_31;
    QLabel *label_error_4;
    QFrame *frame_32;
    QFrame *frame_55;
    QLabel *label_3;
    QFrame *frame_81;
    QFrame *frame_56;
    QStackedWidget *stackedWidget_3;
    QWidget *page_7;
    QTableWidget *tableWidget;
    QLineEdit *lineEdit_68;
    QWidget *page_8;
    QTableWidget *tableWidget_2;
    QLineEdit *lineEdit_69;
    QFrame *frame_57;
    QPushButton *button_podtverkorrert;
    QFrame *frame_67;
    QPushButton *button_otmenakorrert;
    QFrame *frame_68;
    QPushButton *button_null1_3;
    QFrame *frame_69;
    QPushButton *button_null1_4;
    QFrame *frame_70;
    QPushButton *button_korrekt;
    QFrame *frame_71;
    QPushButton *button_null1_6;
    QFrame *frame_72;
    QPushButton *button_null1_7;
    QFrame *frame_73;
    QPushButton *button_backk2;
    QFrame *frame_74;
    QPushButton *button_null1_9;
    QFrame *frame_75;
    QPushButton *button_downwiget2;
    QFrame *frame_76;
    QPushButton *button_leftwiget2;
    QFrame *frame_77;
    QPushButton *button_wiborwiget2;
    QFrame *frame_78;
    QPushButton *button_rightwiget2;
    QFrame *frame_79;
    QPushButton *button_upwiget2;
    QFrame *frame_80;
    QPushButton *button_null1_15;
    QFrame *frame_66;
    QProgressBar *progressBar_runtime_2;
    QLabel *label_time_2;
    QLabel *label_date_2;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *AntonovClass)
    {
        if (AntonovClass->objectName().isEmpty())
            AntonovClass->setObjectName("AntonovClass");
        AntonovClass->resize(980, 916);
        AntonovClass->setMinimumSize(QSize(980, 916));
        AntonovClass->setMaximumSize(QSize(980, 916));
        centralWidget = new QWidget(AntonovClass);
        centralWidget->setObjectName("centralWidget");
        centralWidget->setMinimumSize(QSize(964, 895));
        centralWidget->setMaximumSize(QSize(964, 895));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 0, 961, 871));
        stackedWidget->setMinimumSize(QSize(961, 871));
        stackedWidget->setMaximumSize(QSize(961, 871));
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        frame_5 = new QFrame(page_3);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(0, 0, 121, 61));
        frame_5->setFrameShape(QFrame::Shape::Box);
        frame_5->setFrameShadow(QFrame::Shadow::Plain);
        frame_5->setLineWidth(2);
        label_2 = new QLabel(frame_5);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(0, 0, 121, 61));
        label_2->setPixmap(QPixmap(QString::fromUtf8("../../MAG_DEV_FILES/3.png")));
        frame_6 = new QFrame(frame_5);
        frame_6->setObjectName("frame_6");
        frame_6->setGeometry(QRect(0, 0, 121, 61));
        frame_6->setFrameShape(QFrame::Shape::Box);
        frame_6->setFrameShadow(QFrame::Shadow::Plain);
        frame_6->setLineWidth(2);
        frame_11 = new QFrame(page_3);
        frame_11->setObjectName("frame_11");
        frame_11->setGeometry(QRect(0, 790, 961, 81));
        frame_11->setFrameShape(QFrame::Shape::Box);
        frame_11->setFrameShadow(QFrame::Shadow::Plain);
        frame_22 = new QFrame(frame_11);
        frame_22->setObjectName("frame_22");
        frame_22->setGeometry(QRect(840, 0, 121, 81));
        frame_22->setFrameShape(QFrame::Shape::Box);
        frame_22->setFrameShadow(QFrame::Shadow::Plain);
        button_back = new QPushButton(frame_22);
        button_back->setObjectName("button_back");
        button_back->setGeometry(QRect(0, 0, 121, 81));
        frame_23 = new QFrame(frame_11);
        frame_23->setObjectName("frame_23");
        frame_23->setGeometry(QRect(720, 0, 121, 81));
        frame_23->setFrameShape(QFrame::Shape::Box);
        frame_23->setFrameShadow(QFrame::Shadow::Plain);
        button_startkadr = new QPushButton(frame_23);
        button_startkadr->setObjectName("button_startkadr");
        button_startkadr->setGeometry(QRect(0, 0, 121, 81));
        frame_24 = new QFrame(frame_11);
        frame_24->setObjectName("frame_24");
        frame_24->setGeometry(QRect(600, 0, 121, 81));
        frame_24->setFrameShape(QFrame::Shape::Box);
        frame_24->setFrameShadow(QFrame::Shadow::Plain);
        button_nulllll = new QPushButton(frame_24);
        button_nulllll->setObjectName("button_nulllll");
        button_nulllll->setGeometry(QRect(0, 0, 121, 81));
        frame_25 = new QFrame(frame_11);
        frame_25->setObjectName("frame_25");
        frame_25->setGeometry(QRect(480, 0, 121, 81));
        frame_25->setFrameShape(QFrame::Shape::Box);
        frame_25->setFrameShadow(QFrame::Shadow::Plain);
        button_smesh = new QPushButton(frame_25);
        button_smesh->setObjectName("button_smesh");
        button_smesh->setGeometry(QRect(0, 0, 121, 81));
        frame_26 = new QFrame(frame_11);
        frame_26->setObjectName("frame_26");
        frame_26->setGeometry(QRect(360, 0, 121, 81));
        frame_26->setFrameShape(QFrame::Shape::Box);
        frame_26->setFrameShadow(QFrame::Shadow::Plain);
        button_null3 = new QPushButton(frame_26);
        button_null3->setObjectName("button_null3");
        button_null3->setGeometry(QRect(0, 0, 121, 81));
        frame_27 = new QFrame(frame_11);
        frame_27->setObjectName("frame_27");
        frame_27->setGeometry(QRect(240, 0, 121, 81));
        frame_27->setFrameShape(QFrame::Shape::Box);
        frame_27->setFrameShadow(QFrame::Shadow::Plain);
        button_null2 = new QPushButton(frame_27);
        button_null2->setObjectName("button_null2");
        button_null2->setGeometry(QRect(0, 0, 121, 81));
        frame_28 = new QFrame(frame_11);
        frame_28->setObjectName("frame_28");
        frame_28->setGeometry(QRect(120, 0, 121, 81));
        frame_28->setFrameShape(QFrame::Shape::Box);
        frame_28->setFrameShadow(QFrame::Shadow::Plain);
        button_null100 = new QPushButton(frame_28);
        button_null100->setObjectName("button_null100");
        button_null100->setGeometry(QRect(0, 0, 121, 81));
        frame_29 = new QFrame(frame_11);
        frame_29->setObjectName("frame_29");
        frame_29->setGeometry(QRect(0, 0, 121, 81));
        frame_29->setFrameShape(QFrame::Shape::Box);
        frame_29->setFrameShadow(QFrame::Shadow::Plain);
        button_selectprog = new QPushButton(frame_29);
        button_selectprog->setObjectName("button_selectprog");
        button_selectprog->setGeometry(QRect(0, 0, 121, 81));
        frame_8 = new QFrame(page_3);
        frame_8->setObjectName("frame_8");
        frame_8->setGeometry(QRect(650, 0, 191, 61));
        frame_8->setFrameShape(QFrame::Shape::Box);
        frame_8->setFrameShadow(QFrame::Shadow::Plain);
        frame_8->setLineWidth(2);
        frame_10 = new QFrame(page_3);
        frame_10->setObjectName("frame_10");
        frame_10->setGeometry(QRect(840, 0, 121, 791));
        frame_10->setFrameShape(QFrame::Shape::Box);
        frame_10->setFrameShadow(QFrame::Shadow::Plain);
        frame_10->setLineWidth(2);
        progressBar_runtime = new QProgressBar(frame_10);
        progressBar_runtime->setObjectName("progressBar_runtime");
        progressBar_runtime->setGeometry(QRect(10, 160, 99, 24));
        progressBar_runtime->setValue(0);
        progressBar_runtime->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_time = new QLabel(frame_10);
        label_time->setObjectName("label_time");
        label_time->setGeometry(QRect(10, 90, 99, 29));
        QFont font;
        font.setFamilies({QString::fromUtf8("Times New Roman")});
        font.setPointSize(11);
        font.setBold(true);
        label_time->setFont(font);
        label_time->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_date = new QLabel(frame_10);
        label_date->setObjectName("label_date");
        label_date->setGeometry(QRect(10, 10, 99, 29));
        label_date->setFont(font);
        label_date->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_15 = new QFrame(frame_10);
        frame_15->setObjectName("frame_15");
        frame_15->setGeometry(QRect(0, 230, 121, 81));
        frame_15->setFrameShape(QFrame::Shape::Box);
        frame_15->setFrameShadow(QFrame::Shadow::Plain);
        button_numeration = new QPushButton(frame_15);
        button_numeration->setObjectName("button_numeration");
        button_numeration->setGeometry(QRect(0, 0, 121, 81));
        frame_16 = new QFrame(frame_10);
        frame_16->setObjectName("frame_16");
        frame_16->setGeometry(QRect(0, 310, 121, 81));
        frame_16->setFrameShape(QFrame::Shape::Box);
        frame_16->setFrameShadow(QFrame::Shadow::Plain);
        button_smenaekrana = new QPushButton(frame_16);
        button_smenaekrana->setObjectName("button_smenaekrana");
        button_smenaekrana->setGeometry(QRect(0, 0, 121, 81));
        frame_17 = new QFrame(frame_10);
        frame_17->setObjectName("frame_17");
        frame_17->setGeometry(QRect(0, 390, 121, 81));
        frame_17->setFrameShape(QFrame::Shape::Box);
        frame_17->setFrameShadow(QFrame::Shadow::Plain);
        button_mmdyum = new QPushButton(frame_17);
        button_mmdyum->setObjectName("button_mmdyum");
        button_mmdyum->setGeometry(QRect(0, 0, 121, 81));
        frame_18 = new QFrame(frame_10);
        frame_18->setObjectName("frame_18");
        frame_18->setGeometry(QRect(0, 470, 121, 81));
        frame_18->setFrameShape(QFrame::Shape::Box);
        frame_18->setFrameShadow(QFrame::Shadow::Plain);
        button_changesk = new QPushButton(frame_18);
        button_changesk->setObjectName("button_changesk");
        button_changesk->setGeometry(QRect(0, 0, 121, 81));
        frame_19 = new QFrame(frame_10);
        frame_19->setObjectName("frame_19");
        frame_19->setGeometry(QRect(0, 550, 121, 81));
        frame_19->setFrameShape(QFrame::Shape::Box);
        frame_19->setFrameShadow(QFrame::Shadow::Plain);
        button_priv = new QPushButton(frame_19);
        button_priv->setObjectName("button_priv");
        button_priv->setGeometry(QRect(0, 0, 121, 81));
        frame_20 = new QFrame(frame_10);
        frame_20->setObjectName("frame_20");
        frame_20->setGeometry(QRect(0, 630, 121, 81));
        frame_20->setFrameShape(QFrame::Shape::Box);
        frame_20->setFrameShadow(QFrame::Shadow::Plain);
        button_null4 = new QPushButton(frame_20);
        button_null4->setObjectName("button_null4");
        button_null4->setGeometry(QRect(0, 0, 121, 81));
        frame_21 = new QFrame(frame_10);
        frame_21->setObjectName("frame_21");
        frame_21->setGeometry(QRect(0, 710, 121, 81));
        frame_21->setFrameShape(QFrame::Shape::Box);
        frame_21->setFrameShadow(QFrame::Shadow::Plain);
        button_privyazka = new QPushButton(frame_21);
        button_privyazka->setObjectName("button_privyazka");
        button_privyazka->setGeometry(QRect(0, 0, 121, 81));
        frame_7 = new QFrame(page_3);
        frame_7->setObjectName("frame_7");
        frame_7->setGeometry(QRect(120, 0, 531, 61));
        frame_7->setFrameShape(QFrame::Shape::Box);
        frame_7->setFrameShadow(QFrame::Shadow::Plain);
        frame_7->setLineWidth(2);
        label_chanel = new QLabel(frame_7);
        label_chanel->setObjectName("label_chanel");
        label_chanel->setGeometry(QRect(380, 10, 81, 41));
        label_chanel->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_sostoyanine = new QLabel(frame_7);
        label_sostoyanine->setObjectName("label_sostoyanine");
        label_sostoyanine->setGeometry(QRect(180, 10, 121, 41));
        label_sostoyanine->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_rejim_isp = new QLabel(frame_7);
        label_rejim_isp->setObjectName("label_rejim_isp");
        label_rejim_isp->setGeometry(QRect(40, 10, 81, 41));
        label_rejim_isp->setAlignment(Qt::AlignmentFlag::AlignCenter);
        dockWidget = new QDockWidget(page_3);
        dockWidget->setObjectName("dockWidget");
        dockWidget->setGeometry(QRect(0, 110, 441, 221));
        dockWidgetContents = new QWidget();
        dockWidgetContents->setObjectName("dockWidgetContents");
        label_sksskd = new QLabel(dockWidgetContents);
        label_sksskd->setObjectName("label_sksskd");
        label_sksskd->setGeometry(QRect(20, 10, 91, 21));
        label_sksskd->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_z_value_current = new QLabel(dockWidgetContents);
        label_z_value_current->setObjectName("label_z_value_current");
        label_z_value_current->setGeometry(QRect(162, 155, 111, 31));
        label_z_value_current->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_z_axis = new QLineEdit(dockWidgetContents);
        label_z_axis->setObjectName("label_z_axis");
        label_z_axis->setGeometry(QRect(12, 155, 113, 31));
        label_z_axis->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_z_axis->setReadOnly(true);
        lineEdit_4 = new QLineEdit(dockWidgetContents);
        lineEdit_4->setObjectName("lineEdit_4");
        lineEdit_4->setGeometry(QRect(162, 5, 113, 31));
        lineEdit_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_4->setReadOnly(true);
        label_y_value_current = new QLabel(dockWidgetContents);
        label_y_value_current->setObjectName("label_y_value_current");
        label_y_value_current->setGeometry(QRect(162, 105, 111, 31));
        label_y_value_current->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_3 = new QLineEdit(dockWidgetContents);
        lineEdit_3->setObjectName("lineEdit_3");
        lineEdit_3->setGeometry(QRect(302, 5, 113, 31));
        lineEdit_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_3->setReadOnly(true);
        label_y_value_final = new QLabel(dockWidgetContents);
        label_y_value_final->setObjectName("label_y_value_final");
        label_y_value_final->setGeometry(QRect(302, 105, 111, 31));
        label_y_value_final->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_x_value_final = new QLabel(dockWidgetContents);
        label_x_value_final->setObjectName("label_x_value_final");
        label_x_value_final->setGeometry(QRect(302, 55, 111, 31));
        label_x_value_final->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_z_value_final = new QLabel(dockWidgetContents);
        label_z_value_final->setObjectName("label_z_value_final");
        label_z_value_final->setGeometry(QRect(302, 155, 111, 31));
        label_z_value_final->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_y_axis = new QLineEdit(dockWidgetContents);
        label_y_axis->setObjectName("label_y_axis");
        label_y_axis->setGeometry(QRect(12, 105, 113, 31));
        label_y_axis->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_y_axis->setReadOnly(true);
        frame_3 = new QFrame(dockWidgetContents);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(12, 5, 111, 31));
        frame_3->setFrameShape(QFrame::Shape::Box);
        frame_3->setFrameShadow(QFrame::Shadow::Plain);
        label_x_value_current = new QLabel(dockWidgetContents);
        label_x_value_current->setObjectName("label_x_value_current");
        label_x_value_current->setGeometry(QRect(162, 55, 111, 31));
        label_x_value_current->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_x_axis = new QLineEdit(dockWidgetContents);
        label_x_axis->setObjectName("label_x_axis");
        label_x_axis->setGeometry(QRect(12, 55, 113, 31));
        label_x_axis->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_x_axis->setReadOnly(true);
        dockWidget->setWidget(dockWidgetContents);
        dockWidget_2 = new QDockWidget(page_3);
        dockWidget_2->setObjectName("dockWidget_2");
        dockWidget_2->setGeometry(QRect(0, 340, 441, 331));
        dockWidgetContents_2 = new QWidget();
        dockWidgetContents_2->setObjectName("dockWidgetContents_2");
        stackedWidget_winchan = new QStackedWidget(dockWidgetContents_2);
        stackedWidget_winchan->setObjectName("stackedWidget_winchan");
        stackedWidget_winchan->setGeometry(QRect(10, 0, 421, 301));
        page = new QWidget();
        page->setObjectName("page");
        textEdit = new QTextEdit(page);
        textEdit->setObjectName("textEdit");
        textEdit->setGeometry(QRect(0, 10, 411, 31));
        textEdit->setFrameShadow(QFrame::Shadow::Raised);
        textEdit->setReadOnly(true);
        label_t_code_3 = new QLabel(page);
        label_t_code_3->setObjectName("label_t_code_3");
        label_t_code_3->setGeometry(QRect(370, 140, 41, 31));
        label_t_code_3->setFrameShape(QFrame::Shape::Box);
        label_t_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_20 = new QLabel(page);
        label_g_code_20->setObjectName("label_g_code_20");
        label_g_code_20->setGeometry(QRect(0, 230, 41, 31));
        label_g_code_20->setFrameShape(QFrame::Shape::Box);
        label_g_code_20->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_8 = new QLabel(page);
        label_g_code_8->setObjectName("label_g_code_8");
        label_g_code_8->setGeometry(QRect(200, 140, 41, 31));
        label_g_code_8->setFrameShape(QFrame::Shape::Box);
        label_g_code_8->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_4 = new QLabel(page);
        label_d_code_4->setObjectName("label_d_code_4");
        label_d_code_4->setGeometry(QRect(330, 200, 41, 31));
        label_d_code_4->setFrameShape(QFrame::Shape::Box);
        label_d_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_3 = new QLabel(page);
        label_d_code_3->setObjectName("label_d_code_3");
        label_d_code_3->setGeometry(QRect(330, 170, 41, 31));
        label_d_code_3->setFrameShape(QFrame::Shape::Box);
        label_d_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_13 = new QLabel(page);
        label_g_code_13->setObjectName("label_g_code_13");
        label_g_code_13->setGeometry(QRect(160, 170, 41, 31));
        label_g_code_13->setFrameShape(QFrame::Shape::Box);
        label_g_code_13->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_11 = new QLabel(page);
        label_g_code_11->setObjectName("label_g_code_11");
        label_g_code_11->setGeometry(QRect(80, 170, 41, 31));
        label_g_code_11->setFrameShape(QFrame::Shape::Box);
        label_g_code_11->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_27 = new QLabel(page);
        label_g_code_27->setObjectName("label_g_code_27");
        label_g_code_27->setGeometry(QRect(80, 260, 41, 31));
        label_g_code_27->setFrameShape(QFrame::Shape::Box);
        label_g_code_27->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code = new QLabel(page);
        label_d_code->setObjectName("label_d_code");
        label_d_code->setGeometry(QRect(200, 70, 41, 31));
        label_d_code->setFrameShape(QFrame::Shape::Box);
        label_d_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_4 = new QLabel(page);
        label_m_code_4->setObjectName("label_m_code_4");
        label_m_code_4->setGeometry(QRect(290, 170, 41, 31));
        label_m_code_4->setFrameShape(QFrame::Shape::Box);
        label_m_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_6 = new QLabel(page);
        label_m_code_6->setObjectName("label_m_code_6");
        label_m_code_6->setGeometry(QRect(290, 230, 41, 31));
        label_m_code_6->setFrameShape(QFrame::Shape::Box);
        label_m_code_6->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_10 = new QLabel(page);
        label_g_code_10->setObjectName("label_g_code_10");
        label_g_code_10->setGeometry(QRect(40, 170, 41, 31));
        label_g_code_10->setFrameShape(QFrame::Shape::Box);
        label_g_code_10->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_7 = new QLabel(page);
        label_g_code_7->setObjectName("label_g_code_7");
        label_g_code_7->setGeometry(QRect(160, 140, 41, 31));
        label_g_code_7->setFrameShape(QFrame::Shape::Box);
        label_g_code_7->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_16 = new QLabel(page);
        label_g_code_16->setObjectName("label_g_code_16");
        label_g_code_16->setGeometry(QRect(160, 200, 41, 31));
        label_g_code_16->setFrameShape(QFrame::Shape::Box);
        label_g_code_16->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_12 = new QLabel(page);
        label_g_code_12->setObjectName("label_g_code_12");
        label_g_code_12->setGeometry(QRect(120, 170, 41, 31));
        label_g_code_12->setFrameShape(QFrame::Shape::Box);
        label_g_code_12->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_26 = new QLabel(page);
        label_g_code_26->setObjectName("label_g_code_26");
        label_g_code_26->setGeometry(QRect(40, 260, 41, 31));
        label_g_code_26->setFrameShape(QFrame::Shape::Box);
        label_g_code_26->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_2 = new QLabel(page);
        label_m_code_2->setObjectName("label_m_code_2");
        label_m_code_2->setGeometry(QRect(290, 260, 41, 31));
        label_m_code_2->setFrameShape(QFrame::Shape::Box);
        label_m_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_6 = new QLabel(page);
        label_g_code_6->setObjectName("label_g_code_6");
        label_g_code_6->setGeometry(QRect(120, 140, 41, 31));
        label_g_code_6->setFrameShape(QFrame::Shape::Box);
        label_g_code_6->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_2 = new QLabel(page);
        label_t_code_2->setObjectName("label_t_code_2");
        label_t_code_2->setGeometry(QRect(160, 70, 41, 31));
        label_t_code_2->setFrameShape(QFrame::Shape::Box);
        label_t_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_21 = new QLabel(page);
        label_g_code_21->setObjectName("label_g_code_21");
        label_g_code_21->setGeometry(QRect(40, 230, 41, 31));
        label_g_code_21->setFrameShape(QFrame::Shape::Box);
        label_g_code_21->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_2 = new QLabel(page);
        label_g_code_2->setObjectName("label_g_code_2");
        label_g_code_2->setGeometry(QRect(120, 200, 41, 31));
        label_g_code_2->setFrameShape(QFrame::Shape::Box);
        label_g_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_5 = new QLabel(page);
        label_m_code_5->setObjectName("label_m_code_5");
        label_m_code_5->setGeometry(QRect(290, 200, 41, 31));
        label_m_code_5->setFrameShape(QFrame::Shape::Box);
        label_m_code_5->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_9 = new QLabel(page);
        label_g_code_9->setObjectName("label_g_code_9");
        label_g_code_9->setGeometry(QRect(0, 170, 41, 31));
        label_g_code_9->setFrameShape(QFrame::Shape::Box);
        label_g_code_9->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code = new QLabel(page);
        label_g_code->setObjectName("label_g_code");
        label_g_code->setGeometry(QRect(200, 260, 41, 31));
        label_g_code->setFrameShape(QFrame::Shape::Box);
        label_g_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code = new QLabel(page);
        label_m_code->setObjectName("label_m_code");
        label_m_code->setGeometry(QRect(290, 140, 41, 31));
        label_m_code->setFrameShape(QFrame::Shape::Box);
        label_m_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_3 = new QLabel(page);
        label_m_code_3->setObjectName("label_m_code_3");
        label_m_code_3->setGeometry(QRect(330, 230, 41, 31));
        label_m_code_3->setFrameShape(QFrame::Shape::Box);
        label_m_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_3 = new QLabel(page);
        label_g_code_3->setObjectName("label_g_code_3");
        label_g_code_3->setGeometry(QRect(0, 140, 41, 31));
        label_g_code_3->setFrameShape(QFrame::Shape::Box);
        label_g_code_3->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_15 = new QLabel(page);
        label_g_code_15->setObjectName("label_g_code_15");
        label_g_code_15->setGeometry(QRect(200, 200, 41, 31));
        label_g_code_15->setFrameShape(QFrame::Shape::Box);
        label_g_code_15->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_14 = new QLabel(page);
        label_g_code_14->setObjectName("label_g_code_14");
        label_g_code_14->setGeometry(QRect(200, 170, 41, 31));
        label_g_code_14->setFrameShape(QFrame::Shape::Box);
        label_g_code_14->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_22 = new QLabel(page);
        label_g_code_22->setObjectName("label_g_code_22");
        label_g_code_22->setGeometry(QRect(80, 230, 41, 31));
        label_g_code_22->setFrameShape(QFrame::Shape::Box);
        label_g_code_22->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_m_code_1 = new QLabel(page);
        label_m_code_1->setObjectName("label_m_code_1");
        label_m_code_1->setGeometry(QRect(330, 260, 41, 31));
        label_m_code_1->setFrameShape(QFrame::Shape::Box);
        label_m_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_23 = new QLabel(page);
        label_g_code_23->setObjectName("label_g_code_23");
        label_g_code_23->setGeometry(QRect(160, 230, 41, 31));
        label_g_code_23->setFrameShape(QFrame::Shape::Box);
        label_g_code_23->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_19 = new QLabel(page);
        label_g_code_19->setObjectName("label_g_code_19");
        label_g_code_19->setGeometry(QRect(0, 200, 41, 31));
        label_g_code_19->setFrameShape(QFrame::Shape::Box);
        label_g_code_19->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_2 = new QLabel(page);
        label_d_code_2->setObjectName("label_d_code_2");
        label_d_code_2->setGeometry(QRect(40, 70, 41, 31));
        label_d_code_2->setFrameShape(QFrame::Shape::Box);
        label_d_code_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_17 = new QLabel(page);
        label_g_code_17->setObjectName("label_g_code_17");
        label_g_code_17->setGeometry(QRect(80, 200, 41, 31));
        label_g_code_17->setFrameShape(QFrame::Shape::Box);
        label_g_code_17->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_4 = new QLabel(page);
        label_g_code_4->setObjectName("label_g_code_4");
        label_g_code_4->setGeometry(QRect(40, 140, 41, 31));
        label_g_code_4->setFrameShape(QFrame::Shape::Box);
        label_g_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_1 = new QLabel(page);
        label_t_code_1->setObjectName("label_t_code_1");
        label_t_code_1->setGeometry(QRect(370, 260, 41, 31));
        label_t_code_1->setFrameShape(QFrame::Shape::Box);
        label_t_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_24 = new QLabel(page);
        label_g_code_24->setObjectName("label_g_code_24");
        label_g_code_24->setGeometry(QRect(200, 230, 41, 31));
        label_g_code_24->setFrameShape(QFrame::Shape::Box);
        label_g_code_24->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_1 = new QLabel(page);
        label_g_code_1->setObjectName("label_g_code_1");
        label_g_code_1->setGeometry(QRect(120, 230, 41, 31));
        label_g_code_1->setFrameShape(QFrame::Shape::Box);
        label_g_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_29 = new QLabel(page);
        label_g_code_29->setObjectName("label_g_code_29");
        label_g_code_29->setGeometry(QRect(160, 260, 41, 31));
        label_g_code_29->setFrameShape(QFrame::Shape::Box);
        label_g_code_29->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code = new QLabel(page);
        label_t_code->setObjectName("label_t_code");
        label_t_code->setGeometry(QRect(0, 70, 41, 31));
        label_t_code->setFrameShape(QFrame::Shape::Box);
        label_t_code->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_25 = new QLabel(page);
        label_g_code_25->setObjectName("label_g_code_25");
        label_g_code_25->setGeometry(QRect(0, 260, 41, 31));
        label_g_code_25->setFrameShape(QFrame::Shape::Box);
        label_g_code_25->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_d_code_1 = new QLabel(page);
        label_d_code_1->setObjectName("label_d_code_1");
        label_d_code_1->setGeometry(QRect(330, 140, 41, 31));
        label_d_code_1->setFrameShape(QFrame::Shape::Box);
        label_d_code_1->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_6 = new QLabel(page);
        label_t_code_6->setObjectName("label_t_code_6");
        label_t_code_6->setGeometry(QRect(370, 230, 41, 31));
        label_t_code_6->setFrameShape(QFrame::Shape::Box);
        label_t_code_6->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_28 = new QLabel(page);
        label_g_code_28->setObjectName("label_g_code_28");
        label_g_code_28->setGeometry(QRect(120, 260, 41, 31));
        label_g_code_28->setFrameShape(QFrame::Shape::Box);
        label_g_code_28->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_4 = new QLabel(page);
        label_t_code_4->setObjectName("label_t_code_4");
        label_t_code_4->setGeometry(QRect(370, 170, 41, 31));
        label_t_code_4->setFrameShape(QFrame::Shape::Box);
        label_t_code_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_5 = new QLabel(page);
        label_g_code_5->setObjectName("label_g_code_5");
        label_g_code_5->setGeometry(QRect(80, 140, 41, 31));
        label_g_code_5->setFrameShape(QFrame::Shape::Box);
        label_g_code_5->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_g_code_18 = new QLabel(page);
        label_g_code_18->setObjectName("label_g_code_18");
        label_g_code_18->setGeometry(QRect(40, 200, 41, 31));
        label_g_code_18->setFrameShape(QFrame::Shape::Box);
        label_g_code_18->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_t_code_5 = new QLabel(page);
        label_t_code_5->setObjectName("label_t_code_5");
        label_t_code_5->setGeometry(QRect(370, 200, 41, 31));
        label_t_code_5->setFrameShape(QFrame::Shape::Box);
        label_t_code_5->setAlignment(Qt::AlignmentFlag::AlignCenter);
        stackedWidget_winchan->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        graphView_simul = new QGraphicsView(page_2);
        graphView_simul->setObjectName("graphView_simul");
        graphView_simul->setGeometry(QRect(0, 0, 421, 311));
        stackedWidget_winchan->addWidget(page_2);
        dockWidget_2->setWidget(dockWidgetContents_2);
        dockWidget_3 = new QDockWidget(page_3);
        dockWidget_3->setObjectName("dockWidget_3");
        dockWidget_3->setGeometry(QRect(0, 660, 441, 121));
        dockWidgetContents_3 = new QWidget();
        dockWidgetContents_3->setObjectName("dockWidgetContents_3");
        commandLinkButton_start = new QCommandLinkButton(dockWidgetContents_3);
        commandLinkButton_start->setObjectName("commandLinkButton_start");
        commandLinkButton_start->setGeometry(QRect(320, 0, 101, 41));
        commandLinkButton_start->setAutoFillBackground(false);
        QIcon icon(QIcon::fromTheme(QString::fromUtf8("QIcon::ThemeIcon::MediaPlaybackStart")));
        commandLinkButton_start->setIcon(icon);
        commandLinkButton_reset = new QCommandLinkButton(dockWidgetContents_3);
        commandLinkButton_reset->setObjectName("commandLinkButton_reset");
        commandLinkButton_reset->setGeometry(QRect(10, 50, 101, 41));
        QIcon icon1(QIcon::fromTheme(QString::fromUtf8("QIcon::ThemeIcon::SystemReboot")));
        commandLinkButton_reset->setIcon(icon1);
        commandLinkButton_reset->setAutoDefault(false);
        commandLinkButton_resetalarms = new QCommandLinkButton(dockWidgetContents_3);
        commandLinkButton_resetalarms->setObjectName("commandLinkButton_resetalarms");
        commandLinkButton_resetalarms->setGeometry(QRect(10, 0, 121, 41));
        commandLinkButton_resetalarms->setIcon(icon1);
        commandLinkButton_resetalarms->setAutoDefault(false);
        commandLinkButton_stop = new QCommandLinkButton(dockWidgetContents_3);
        commandLinkButton_stop->setObjectName("commandLinkButton_stop");
        commandLinkButton_stop->setGeometry(QRect(320, 50, 101, 41));
        QIcon icon2(QIcon::fromTheme(QString::fromUtf8("QIcon::ThemeIcon::WindowClose")));
        commandLinkButton_stop->setIcon(icon2);
        dockWidget_3->setWidget(dockWidgetContents_3);
        dockWidget_4 = new QDockWidget(page_3);
        dockWidget_4->setObjectName("dockWidget_4");
        dockWidget_4->setGeometry(QRect(440, 700, 301, 80));
        dockWidgetContents_4 = new QWidget();
        dockWidgetContents_4->setObjectName("dockWidgetContents_4");
        info_line = new QLabel(dockWidgetContents_4);
        info_line->setObjectName("info_line");
        info_line->setGeometry(QRect(0, 0, 301, 61));
        info_line->setLineWidth(2);
        info_line->setAlignment(Qt::AlignmentFlag::AlignCenter);
        dockWidget_4->setWidget(dockWidgetContents_4);
        dockWidget_5 = new QDockWidget(page_3);
        dockWidget_5->setObjectName("dockWidget_5");
        dockWidget_5->setGeometry(QRect(740, 700, 91, 80));
        dockWidgetContents_5 = new QWidget();
        dockWidgetContents_5->setObjectName("dockWidgetContents_5");
        label_language = new QLabel(dockWidgetContents_5);
        label_language->setObjectName("label_language");
        label_language->setGeometry(QRect(0, 0, 91, 51));
        label_language->setAlignment(Qt::AlignmentFlag::AlignCenter);
        dockWidget_5->setWidget(dockWidgetContents_5);
        dockWidget_6 = new QDockWidget(page_3);
        dockWidget_6->setObjectName("dockWidget_6");
        dockWidget_6->setGeometry(QRect(440, 560, 391, 141));
        dockWidgetContents_6 = new QWidget();
        dockWidgetContents_6->setObjectName("dockWidgetContents_6");
        label_feed_rate = new QLineEdit(dockWidgetContents_6);
        label_feed_rate->setObjectName("label_feed_rate");
        label_feed_rate->setGeometry(QRect(20, 10, 141, 22));
        label_feed_rate->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_feed_rate->setReadOnly(true);
        slider_feed_rate = new QSlider(dockWidgetContents_6);
        slider_feed_rate->setObjectName("slider_feed_rate");
        slider_feed_rate->setGeometry(QRect(20, 70, 141, 22));
        slider_feed_rate->setOrientation(Qt::Orientation::Horizontal);
        label_spindle_speed = new QLineEdit(dockWidgetContents_6);
        label_spindle_speed->setObjectName("label_spindle_speed");
        label_spindle_speed->setGeometry(QRect(232, 10, 141, 22));
        label_spindle_speed->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_spindle_speed->setReadOnly(true);
        label_feed_value = new QLabel(dockWidgetContents_6);
        label_feed_value->setObjectName("label_feed_value");
        label_feed_value->setGeometry(QRect(20, 40, 141, 21));
        label_feed_value->setAlignment(Qt::AlignmentFlag::AlignCenter);
        slider_spindle_speed = new QSlider(dockWidgetContents_6);
        slider_spindle_speed->setObjectName("slider_spindle_speed");
        slider_spindle_speed->setGeometry(QRect(230, 70, 141, 22));
        slider_spindle_speed->setOrientation(Qt::Orientation::Horizontal);
        label_changessk = new QLabel(dockWidgetContents_6);
        label_changessk->setObjectName("label_changessk");
        label_changessk->setGeometry(QRect(340, 40, 49, 21));
        label_spindle_value = new QLabel(dockWidgetContents_6);
        label_spindle_value->setObjectName("label_spindle_value");
        label_spindle_value->setGeometry(QRect(230, 40, 141, 21));
        label_spindle_value->setAlignment(Qt::AlignmentFlag::AlignCenter);
        dockWidget_6->setWidget(dockWidgetContents_6);
        dockWidget_7 = new QDockWidget(page_3);
        dockWidget_7->setObjectName("dockWidget_7");
        dockWidget_7->setGeometry(QRect(440, 110, 391, 451));
        dockWidget_7->setFeatures(QDockWidget::DockWidgetFeature::DockWidgetClosable|QDockWidget::DockWidgetFeature::DockWidgetFloatable|QDockWidget::DockWidgetFeature::DockWidgetMovable);
        dockWidgetContents_7 = new QWidget();
        dockWidgetContents_7->setObjectName("dockWidgetContents_7");
        listWidget_program = new QListWidget(dockWidgetContents_7);
        listWidget_program->setObjectName("listWidget_program");
        listWidget_program->setGeometry(QRect(0, 0, 391, 431));
        dockWidget_7->setWidget(dockWidgetContents_7);
        dockWidget_8 = new QDockWidget(page_3);
        dockWidget_8->setObjectName("dockWidget_8");
        dockWidget_8->setGeometry(QRect(0, 60, 831, 51));
        dockWidgetContents_8 = new QWidget();
        dockWidgetContents_8->setObjectName("dockWidgetContents_8");
        label_error = new QLabel(dockWidgetContents_8);
        label_error->setObjectName("label_error");
        label_error->setGeometry(QRect(20, 0, 791, 21));
        label_error->setAlignment(Qt::AlignmentFlag::AlignCenter);
        dockWidget_8->setWidget(dockWidgetContents_8);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        frame_14 = new QFrame(page_4);
        frame_14->setObjectName("frame_14");
        frame_14->setGeometry(QRect(120, 0, 531, 61));
        frame_14->setFrameShape(QFrame::Shape::Box);
        frame_14->setFrameShadow(QFrame::Shadow::Plain);
        frame_14->setLineWidth(2);
        label_chanel_4 = new QLabel(frame_14);
        label_chanel_4->setObjectName("label_chanel_4");
        label_chanel_4->setGeometry(QRect(380, 10, 81, 41));
        label_chanel_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_sostoyanine_4 = new QLabel(frame_14);
        label_sostoyanine_4->setObjectName("label_sostoyanine_4");
        label_sostoyanine_4->setGeometry(QRect(180, 10, 121, 41));
        label_sostoyanine_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_rejim_isp_4 = new QLabel(frame_14);
        label_rejim_isp_4->setObjectName("label_rejim_isp_4");
        label_rejim_isp_4->setGeometry(QRect(40, 10, 81, 41));
        label_rejim_isp_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_31 = new QFrame(page_4);
        frame_31->setObjectName("frame_31");
        frame_31->setGeometry(QRect(0, 60, 841, 51));
        frame_31->setFrameShape(QFrame::Shape::Box);
        frame_31->setFrameShadow(QFrame::Shadow::Plain);
        frame_31->setLineWidth(2);
        label_error_4 = new QLabel(frame_31);
        label_error_4->setObjectName("label_error_4");
        label_error_4->setGeometry(QRect(20, 0, 821, 51));
        label_error_4->setAlignment(Qt::AlignmentFlag::AlignCenter);
        frame_32 = new QFrame(page_4);
        frame_32->setObjectName("frame_32");
        frame_32->setGeometry(QRect(650, 0, 191, 61));
        frame_32->setFrameShape(QFrame::Shape::Box);
        frame_32->setFrameShadow(QFrame::Shadow::Plain);
        frame_32->setLineWidth(2);
        frame_55 = new QFrame(page_4);
        frame_55->setObjectName("frame_55");
        frame_55->setGeometry(QRect(0, 0, 121, 61));
        frame_55->setFrameShape(QFrame::Shape::Box);
        frame_55->setFrameShadow(QFrame::Shadow::Plain);
        frame_55->setLineWidth(2);
        label_3 = new QLabel(frame_55);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(0, 0, 121, 61));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../../MAG_DEV_FILES/3.png")));
        frame_81 = new QFrame(frame_55);
        frame_81->setObjectName("frame_81");
        frame_81->setGeometry(QRect(0, 0, 121, 61));
        frame_81->setFrameShape(QFrame::Shape::Box);
        frame_81->setFrameShadow(QFrame::Shadow::Plain);
        frame_81->setLineWidth(2);
        frame_56 = new QFrame(page_4);
        frame_56->setObjectName("frame_56");
        frame_56->setGeometry(QRect(0, 110, 841, 651));
        frame_56->setFrameShape(QFrame::Shape::Box);
        frame_56->setFrameShadow(QFrame::Shadow::Plain);
        frame_56->setLineWidth(2);
        stackedWidget_3 = new QStackedWidget(frame_56);
        stackedWidget_3->setObjectName("stackedWidget_3");
        stackedWidget_3->setGeometry(QRect(10, 10, 821, 631));
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        tableWidget = new QTableWidget(page_7);
        if (tableWidget->columnCount() < 4)
            tableWidget->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        if (tableWidget->rowCount() < 8)
            tableWidget->setRowCount(8);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(6, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(7, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget->setItem(0, 0, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget->setItem(0, 1, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget->setItem(0, 2, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget->setItem(0, 3, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget->setItem(1, 0, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget->setItem(1, 1, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget->setItem(1, 2, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget->setItem(1, 3, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget->setItem(2, 0, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget->setItem(2, 1, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget->setItem(2, 2, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget->setItem(2, 3, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget->setItem(3, 0, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget->setItem(3, 1, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget->setItem(3, 2, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget->setItem(3, 3, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget->setItem(4, 0, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget->setItem(4, 1, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget->setItem(4, 2, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget->setItem(4, 3, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget->setItem(5, 0, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget->setItem(5, 1, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget->setItem(5, 2, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWidget->setItem(5, 3, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWidget->setItem(6, 0, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWidget->setItem(6, 1, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget->setItem(6, 2, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWidget->setItem(6, 3, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget->setItem(7, 0, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWidget->setItem(7, 1, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget->setItem(7, 2, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWidget->setItem(7, 3, __qtablewidgetitem43);
        tableWidget->setObjectName("tableWidget");
        tableWidget->setGeometry(QRect(0, 30, 821, 601));
        tableWidget->setGridStyle(Qt::PenStyle::SolidLine);
        tableWidget->setSortingEnabled(false);
        tableWidget->horizontalHeader()->setDefaultSectionSize(196);
        tableWidget->verticalHeader()->setMinimumSectionSize(55);
        tableWidget->verticalHeader()->setDefaultSectionSize(71);
        lineEdit_68 = new QLineEdit(page_7);
        lineEdit_68->setObjectName("lineEdit_68");
        lineEdit_68->setGeometry(QRect(0, 0, 821, 22));
        lineEdit_68->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_68->setReadOnly(true);
        stackedWidget_3->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        tableWidget_2 = new QTableWidget(page_8);
        if (tableWidget_2->columnCount() < 4)
            tableWidget_2->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(0, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(1, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(2, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(3, __qtablewidgetitem47);
        if (tableWidget_2->rowCount() < 13)
            tableWidget_2->setRowCount(13);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWidget_2->setItem(0, 0, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        __qtablewidgetitem49->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(0, 1, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        __qtablewidgetitem50->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(0, 2, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        __qtablewidgetitem51->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(1, 1, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        __qtablewidgetitem52->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(1, 2, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        __qtablewidgetitem53->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(2, 1, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        __qtablewidgetitem54->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(2, 2, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        __qtablewidgetitem55->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(3, 1, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        __qtablewidgetitem56->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(3, 2, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        __qtablewidgetitem57->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(4, 1, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        __qtablewidgetitem58->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(4, 2, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        __qtablewidgetitem59->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(5, 1, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        __qtablewidgetitem60->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(5, 2, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        __qtablewidgetitem61->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(6, 1, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        __qtablewidgetitem62->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(6, 2, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        __qtablewidgetitem63->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(7, 1, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        __qtablewidgetitem64->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(7, 2, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        __qtablewidgetitem65->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(8, 1, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        __qtablewidgetitem66->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(8, 2, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        __qtablewidgetitem67->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(9, 1, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        __qtablewidgetitem68->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(9, 2, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        __qtablewidgetitem69->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(10, 1, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        __qtablewidgetitem70->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(10, 2, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        __qtablewidgetitem71->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(11, 1, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        __qtablewidgetitem72->setTextAlignment(Qt::AlignCenter);
        tableWidget_2->setItem(11, 2, __qtablewidgetitem72);
        tableWidget_2->setObjectName("tableWidget_2");
        tableWidget_2->setGeometry(QRect(0, 30, 821, 601));
        tableWidget_2->setMinimumSize(QSize(591, 0));
        tableWidget_2->setLayoutDirection(Qt::LayoutDirection::LeftToRight);
        tableWidget_2->setShowGrid(true);
        tableWidget_2->setGridStyle(Qt::PenStyle::SolidLine);
        tableWidget_2->setRowCount(13);
        tableWidget_2->horizontalHeader()->setDefaultSectionSize(199);
        tableWidget_2->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        tableWidget_2->verticalHeader()->setCascadingSectionResizes(false);
        tableWidget_2->verticalHeader()->setMinimumSectionSize(24);
        tableWidget_2->verticalHeader()->setDefaultSectionSize(40);
        lineEdit_69 = new QLineEdit(page_8);
        lineEdit_69->setObjectName("lineEdit_69");
        lineEdit_69->setGeometry(QRect(0, 0, 821, 22));
        lineEdit_69->setAlignment(Qt::AlignmentFlag::AlignCenter);
        lineEdit_69->setReadOnly(true);
        stackedWidget_3->addWidget(page_8);
        frame_57 = new QFrame(page_4);
        frame_57->setObjectName("frame_57");
        frame_57->setGeometry(QRect(0, 760, 121, 81));
        frame_57->setFrameShape(QFrame::Shape::Box);
        frame_57->setFrameShadow(QFrame::Shadow::Plain);
        frame_57->setLineWidth(2);
        button_podtverkorrert = new QPushButton(frame_57);
        button_podtverkorrert->setObjectName("button_podtverkorrert");
        button_podtverkorrert->setGeometry(QRect(0, 0, 121, 81));
        frame_67 = new QFrame(page_4);
        frame_67->setObjectName("frame_67");
        frame_67->setGeometry(QRect(120, 760, 121, 81));
        frame_67->setFrameShape(QFrame::Shape::Box);
        frame_67->setFrameShadow(QFrame::Shadow::Plain);
        frame_67->setLineWidth(2);
        button_otmenakorrert = new QPushButton(frame_67);
        button_otmenakorrert->setObjectName("button_otmenakorrert");
        button_otmenakorrert->setGeometry(QRect(0, 0, 121, 81));
        frame_68 = new QFrame(page_4);
        frame_68->setObjectName("frame_68");
        frame_68->setGeometry(QRect(240, 760, 121, 81));
        frame_68->setFrameShape(QFrame::Shape::Box);
        frame_68->setFrameShadow(QFrame::Shadow::Plain);
        frame_68->setLineWidth(2);
        button_null1_3 = new QPushButton(frame_68);
        button_null1_3->setObjectName("button_null1_3");
        button_null1_3->setGeometry(QRect(0, 0, 121, 81));
        frame_69 = new QFrame(page_4);
        frame_69->setObjectName("frame_69");
        frame_69->setGeometry(QRect(360, 760, 121, 81));
        frame_69->setFrameShape(QFrame::Shape::Box);
        frame_69->setFrameShadow(QFrame::Shadow::Plain);
        frame_69->setLineWidth(2);
        button_null1_4 = new QPushButton(frame_69);
        button_null1_4->setObjectName("button_null1_4");
        button_null1_4->setGeometry(QRect(0, 0, 121, 81));
        frame_70 = new QFrame(page_4);
        frame_70->setObjectName("frame_70");
        frame_70->setGeometry(QRect(480, 760, 121, 81));
        frame_70->setFrameShape(QFrame::Shape::Box);
        frame_70->setFrameShadow(QFrame::Shadow::Plain);
        frame_70->setLineWidth(2);
        button_korrekt = new QPushButton(frame_70);
        button_korrekt->setObjectName("button_korrekt");
        button_korrekt->setGeometry(QRect(0, 0, 121, 81));
        frame_71 = new QFrame(page_4);
        frame_71->setObjectName("frame_71");
        frame_71->setGeometry(QRect(600, 760, 121, 81));
        frame_71->setFrameShape(QFrame::Shape::Box);
        frame_71->setFrameShadow(QFrame::Shadow::Plain);
        frame_71->setLineWidth(2);
        button_null1_6 = new QPushButton(frame_71);
        button_null1_6->setObjectName("button_null1_6");
        button_null1_6->setGeometry(QRect(0, 0, 121, 81));
        frame_72 = new QFrame(page_4);
        frame_72->setObjectName("frame_72");
        frame_72->setGeometry(QRect(720, 760, 121, 81));
        frame_72->setFrameShape(QFrame::Shape::Box);
        frame_72->setFrameShadow(QFrame::Shadow::Plain);
        frame_72->setLineWidth(2);
        button_null1_7 = new QPushButton(frame_72);
        button_null1_7->setObjectName("button_null1_7");
        button_null1_7->setGeometry(QRect(0, 0, 121, 81));
        frame_73 = new QFrame(page_4);
        frame_73->setObjectName("frame_73");
        frame_73->setGeometry(QRect(840, 760, 121, 81));
        frame_73->setFrameShape(QFrame::Shape::Box);
        frame_73->setFrameShadow(QFrame::Shadow::Plain);
        frame_73->setLineWidth(2);
        button_backk2 = new QPushButton(frame_73);
        button_backk2->setObjectName("button_backk2");
        button_backk2->setGeometry(QRect(0, 0, 121, 81));
        frame_74 = new QFrame(page_4);
        frame_74->setObjectName("frame_74");
        frame_74->setGeometry(QRect(840, 680, 121, 81));
        frame_74->setFrameShape(QFrame::Shape::Box);
        frame_74->setFrameShadow(QFrame::Shadow::Plain);
        frame_74->setLineWidth(2);
        button_null1_9 = new QPushButton(frame_74);
        button_null1_9->setObjectName("button_null1_9");
        button_null1_9->setGeometry(QRect(0, 0, 121, 81));
        frame_75 = new QFrame(page_4);
        frame_75->setObjectName("frame_75");
        frame_75->setGeometry(QRect(840, 600, 121, 81));
        frame_75->setFrameShape(QFrame::Shape::Box);
        frame_75->setFrameShadow(QFrame::Shadow::Plain);
        frame_75->setLineWidth(2);
        button_downwiget2 = new QPushButton(frame_75);
        button_downwiget2->setObjectName("button_downwiget2");
        button_downwiget2->setGeometry(QRect(0, 0, 121, 81));
        frame_76 = new QFrame(page_4);
        frame_76->setObjectName("frame_76");
        frame_76->setGeometry(QRect(840, 520, 121, 81));
        frame_76->setFrameShape(QFrame::Shape::Box);
        frame_76->setFrameShadow(QFrame::Shadow::Plain);
        frame_76->setLineWidth(2);
        button_leftwiget2 = new QPushButton(frame_76);
        button_leftwiget2->setObjectName("button_leftwiget2");
        button_leftwiget2->setGeometry(QRect(0, 0, 121, 81));
        frame_77 = new QFrame(page_4);
        frame_77->setObjectName("frame_77");
        frame_77->setGeometry(QRect(840, 440, 121, 81));
        frame_77->setFrameShape(QFrame::Shape::Box);
        frame_77->setFrameShadow(QFrame::Shadow::Plain);
        frame_77->setLineWidth(2);
        button_wiborwiget2 = new QPushButton(frame_77);
        button_wiborwiget2->setObjectName("button_wiborwiget2");
        button_wiborwiget2->setGeometry(QRect(0, 0, 121, 81));
        frame_78 = new QFrame(page_4);
        frame_78->setObjectName("frame_78");
        frame_78->setGeometry(QRect(840, 360, 121, 81));
        frame_78->setFrameShape(QFrame::Shape::Box);
        frame_78->setFrameShadow(QFrame::Shadow::Plain);
        frame_78->setLineWidth(2);
        button_rightwiget2 = new QPushButton(frame_78);
        button_rightwiget2->setObjectName("button_rightwiget2");
        button_rightwiget2->setGeometry(QRect(0, 0, 121, 81));
        frame_79 = new QFrame(page_4);
        frame_79->setObjectName("frame_79");
        frame_79->setGeometry(QRect(840, 280, 121, 81));
        frame_79->setFrameShape(QFrame::Shape::Box);
        frame_79->setFrameShadow(QFrame::Shadow::Plain);
        frame_79->setLineWidth(2);
        button_upwiget2 = new QPushButton(frame_79);
        button_upwiget2->setObjectName("button_upwiget2");
        button_upwiget2->setGeometry(QRect(0, 0, 121, 81));
        frame_80 = new QFrame(page_4);
        frame_80->setObjectName("frame_80");
        frame_80->setGeometry(QRect(840, 200, 121, 81));
        frame_80->setFrameShape(QFrame::Shape::Box);
        frame_80->setFrameShadow(QFrame::Shadow::Plain);
        frame_80->setLineWidth(2);
        button_null1_15 = new QPushButton(frame_80);
        button_null1_15->setObjectName("button_null1_15");
        button_null1_15->setGeometry(QRect(0, 0, 121, 81));
        frame_66 = new QFrame(page_4);
        frame_66->setObjectName("frame_66");
        frame_66->setGeometry(QRect(840, 0, 121, 201));
        frame_66->setFrameShape(QFrame::Shape::Box);
        frame_66->setFrameShadow(QFrame::Shadow::Plain);
        frame_66->setLineWidth(2);
        progressBar_runtime_2 = new QProgressBar(frame_66);
        progressBar_runtime_2->setObjectName("progressBar_runtime_2");
        progressBar_runtime_2->setGeometry(QRect(10, 140, 99, 24));
        progressBar_runtime_2->setValue(0);
        progressBar_runtime_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_time_2 = new QLabel(frame_66);
        label_time_2->setObjectName("label_time_2");
        label_time_2->setGeometry(QRect(10, 70, 99, 29));
        label_time_2->setFont(font);
        label_time_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        label_date_2 = new QLabel(frame_66);
        label_date_2->setObjectName("label_date_2");
        label_date_2->setGeometry(QRect(10, 10, 99, 29));
        label_date_2->setFont(font);
        label_date_2->setAlignment(Qt::AlignmentFlag::AlignCenter);
        stackedWidget->addWidget(page_4);
        AntonovClass->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(AntonovClass);
        statusBar->setObjectName("statusBar");
        AntonovClass->setStatusBar(statusBar);

        retranslateUi(AntonovClass);

        stackedWidget->setCurrentIndex(0);
        stackedWidget_winchan->setCurrentIndex(0);
        stackedWidget_3->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(AntonovClass);
    } // setupUi

    void retranslateUi(QMainWindow *AntonovClass)
    {
        AntonovClass->setWindowTitle(QCoreApplication::translate("AntonovClass", "Antonov", nullptr));
        label_2->setText(QString());
        button_back->setText(QCoreApplication::translate("AntonovClass", "\320\222\320\276\320\267\320\262\321\200\320\260\321\202", nullptr));
        button_startkadr->setText(QCoreApplication::translate("AntonovClass", "\320\227\320\260\320\277\321\203\321\201\320\272 \321\201 \n"
"\320\262\321\213\320\261\321\200\320\260\320\275\320\275\320\276\320\263\320\276 \n"
"\320\272\320\260\320\264\321\200\320\260", nullptr));
        button_nulllll->setText(QString());
        button_smesh->setText(QCoreApplication::translate("AntonovClass", "Offset", nullptr));
        button_null3->setText(QString());
        button_null2->setText(QString());
        button_null100->setText(QString());
        button_selectprog->setText(QCoreApplication::translate("AntonovClass", "\320\222\321\213\320\261\320\276\321\200 \n"
"\320\277\321\200\320\276\320\263\321\200\320\260\320\274\320\274\321\213", nullptr));
        label_time->setText(QCoreApplication::translate("AntonovClass", "label_time", nullptr));
        label_date->setText(QCoreApplication::translate("AntonovClass", "label_date", nullptr));
        button_numeration->setText(QCoreApplication::translate("AntonovClass", "\320\235\321\203\320\274\320\265\321\200\320\260\321\206\320\270\321\217", nullptr));
        button_smenaekrana->setText(QCoreApplication::translate("AntonovClass", "\320\241\320\274\320\265\320\275\320\260 \n"
"\321\215\320\272\321\200\320\260\320\275\320\260", nullptr));
        button_mmdyum->setText(QCoreApplication::translate("AntonovClass", "\320\234\320\274 / \320\264\321\216\320\271\320\274", nullptr));
        button_changesk->setText(QCoreApplication::translate("AntonovClass", "\320\241\320\274\320\265\320\275\320\270\321\202\321\214\n"
"\320\265\320\264\320\270\320\275\320\270\321\206\321\213\n"
"\320\277\320\276\320\264\320\260\321\207\320\270", nullptr));
        button_priv->setText(QCoreApplication::translate("AntonovClass", "\320\241\320\274\320\265\320\275\320\260\n"
"\321\201\320\270\321\201\321\202\320\265\320\274\321\213\n"
"\320\272\320\276\320\276\321\200\320\264\320\270\320\275\320\260\321\202", nullptr));
        button_null4->setText(QString());
        button_privyazka->setText(QCoreApplication::translate("AntonovClass", "\320\237\321\200\320\270\320\262\321\217\320\267\320\272\320\260", nullptr));
        label_chanel->setText(QCoreApplication::translate("AntonovClass", "Chanel 1", nullptr));
        label_sostoyanine->setText(QCoreApplication::translate("AntonovClass", "READY TO START", nullptr));
        label_rejim_isp->setText(QCoreApplication::translate("AntonovClass", "AUTO", nullptr));
        label_sksskd->setText(QCoreApplication::translate("AntonovClass", "\320\241\320\232\320\241", nullptr));
        label_z_value_current->setText(QCoreApplication::translate("AntonovClass", "z_0", nullptr));
        label_z_axis->setText(QCoreApplication::translate("AntonovClass", "Z", nullptr));
        lineEdit_4->setText(QCoreApplication::translate("AntonovClass", "\320\242\320\265\320\272\321\203\321\211\320\260\321\217", nullptr));
        label_y_value_current->setText(QCoreApplication::translate("AntonovClass", "y_0", nullptr));
        lineEdit_3->setText(QCoreApplication::translate("AntonovClass", "\320\232\320\276\320\275\320\265\321\207\320\275\320\260\321\217", nullptr));
        label_y_value_final->setText(QCoreApplication::translate("AntonovClass", "y_00", nullptr));
        label_x_value_final->setText(QCoreApplication::translate("AntonovClass", "x_00", nullptr));
        label_z_value_final->setText(QCoreApplication::translate("AntonovClass", "z_00", nullptr));
        label_y_axis->setText(QCoreApplication::translate("AntonovClass", "Y", nullptr));
        label_x_value_current->setText(QCoreApplication::translate("AntonovClass", "x_0", nullptr));
        label_x_axis->setText(QCoreApplication::translate("AntonovClass", "X", nullptr));
        textEdit->setHtml(QCoreApplication::translate("AntonovClass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">\320\220\320\272\321\202\320\270\320\262\320\275\321\213\320\265 \321\204\321\203\320\275\320\272\321\206\320\270\320\270</span></p></body></html>", nullptr));
        label_t_code_3->setText(QString());
        label_g_code_20->setText(QString());
        label_g_code_8->setText(QString());
        label_d_code_4->setText(QString());
        label_d_code_3->setText(QString());
        label_g_code_13->setText(QString());
        label_g_code_11->setText(QString());
        label_g_code_27->setText(QString());
        label_d_code->setText(QString());
        label_m_code_4->setText(QString());
        label_m_code_6->setText(QString());
        label_g_code_10->setText(QString());
        label_g_code_7->setText(QString());
        label_g_code_16->setText(QString());
        label_g_code_12->setText(QString());
        label_g_code_26->setText(QString());
        label_m_code_2->setText(QString());
        label_g_code_6->setText(QString());
        label_t_code_2->setText(QString());
        label_g_code_21->setText(QString());
        label_g_code_2->setText(QString());
        label_m_code_5->setText(QString());
        label_g_code_9->setText(QString());
        label_g_code->setText(QString());
        label_m_code->setText(QString());
        label_m_code_3->setText(QString());
        label_g_code_3->setText(QString());
        label_g_code_15->setText(QString());
        label_g_code_14->setText(QString());
        label_g_code_22->setText(QString());
        label_m_code_1->setText(QString());
        label_g_code_23->setText(QString());
        label_g_code_19->setText(QString());
        label_d_code_2->setText(QString());
        label_g_code_17->setText(QString());
        label_g_code_4->setText(QString());
        label_t_code_1->setText(QString());
        label_g_code_24->setText(QString());
        label_g_code_1->setText(QString());
        label_g_code_29->setText(QString());
        label_t_code->setText(QString());
        label_g_code_25->setText(QString());
        label_d_code_1->setText(QString());
        label_t_code_6->setText(QString());
        label_g_code_28->setText(QString());
        label_t_code_4->setText(QString());
        label_g_code_5->setText(QString());
        label_g_code_18->setText(QString());
        label_t_code_5->setText(QString());
        commandLinkButton_start->setText(QCoreApplication::translate("AntonovClass", "Start", nullptr));
        commandLinkButton_reset->setText(QCoreApplication::translate("AntonovClass", "Reset", nullptr));
        commandLinkButton_resetalarms->setText(QCoreApplication::translate("AntonovClass", "Reset Alarm", nullptr));
        commandLinkButton_stop->setText(QCoreApplication::translate("AntonovClass", "Stop", nullptr));
        info_line->setText(QCoreApplication::translate("AntonovClass", "\320\241\321\202\321\200\320\276\320\272\320\260 \320\270\320\275\321\204\320\276\321\200\320\274\320\260\321\206\320\270\320\270", nullptr));
        label_language->setText(QCoreApplication::translate("AntonovClass", "<html><head/><body><p><span style=\" font-weight:700;\">RU/EN</span></p></body></html>", nullptr));
        label_feed_rate->setText(QCoreApplication::translate("AntonovClass", "\320\237\320\276\320\264\320\260\321\207\320\260", nullptr));
        label_spindle_speed->setText(QCoreApplication::translate("AntonovClass", "\320\236\320\261\320\276\321\200\320\276\321\202\321\213", nullptr));
        label_feed_value->setText(QCoreApplication::translate("AntonovClass", "0", nullptr));
        label_changessk->setText(QCoreApplication::translate("AntonovClass", "\320\274\320\274/\320\274\320\270\320\275", nullptr));
        label_spindle_value->setText(QCoreApplication::translate("AntonovClass", "0", nullptr));
        label_error->setText(QCoreApplication::translate("AntonovClass", "\320\241\321\202\321\200\320\276\320\272\320\260 \320\276\321\210\320\270\320\261\320\276\320\272", nullptr));
        label_chanel_4->setText(QCoreApplication::translate("AntonovClass", "Chanel 1", nullptr));
        label_sostoyanine_4->setText(QCoreApplication::translate("AntonovClass", "READY TO START", nullptr));
        label_rejim_isp_4->setText(QCoreApplication::translate("AntonovClass", "AUTO", nullptr));
        label_error_4->setText(QCoreApplication::translate("AntonovClass", "\320\241\321\202\321\200\320\276\320\272\320\260 \320\276\321\210\320\270\320\261\320\276\320\272", nullptr));
        label_3->setText(QString());
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("AntonovClass", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("AntonovClass", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("AntonovClass", "SP1", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("AntonovClass", "SP3", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->verticalHeaderItem(0);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("AntonovClass", "G54", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->verticalHeaderItem(1);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("AntonovClass", "FINE", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->verticalHeaderItem(2);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("AntonovClass", "G55", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->verticalHeaderItem(3);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("AntonovClass", "FINE", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget->verticalHeaderItem(4);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("AntonovClass", "G56", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget->verticalHeaderItem(5);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("AntonovClass", "FINE", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget->verticalHeaderItem(6);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("AntonovClass", "G57", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget->verticalHeaderItem(7);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("AntonovClass", "FINE", nullptr));

        const bool __sortingEnabled = tableWidget->isSortingEnabled();
        tableWidget->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget->item(0, 0);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget->item(0, 1);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget->item(0, 2);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget->item(0, 3);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget->item(1, 0);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget->item(1, 1);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget->item(1, 2);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget->item(1, 3);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget->item(2, 0);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget->item(2, 1);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget->item(2, 2);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget->item(2, 3);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget->item(3, 0);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget->item(3, 1);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget->item(3, 2);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget->item(3, 3);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget->item(4, 0);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget->item(4, 1);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget->item(4, 2);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget->item(4, 3);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget->item(5, 0);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget->item(5, 1);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget->item(5, 2);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget->item(5, 3);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget->item(6, 0);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget->item(6, 1);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget->item(6, 2);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget->item(6, 3);
        ___qtablewidgetitem39->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget->item(7, 0);
        ___qtablewidgetitem40->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget->item(7, 1);
        ___qtablewidgetitem41->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget->item(7, 2);
        ___qtablewidgetitem42->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget->item(7, 3);
        ___qtablewidgetitem43->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        tableWidget->setSortingEnabled(__sortingEnabled);

        lineEdit_68->setText(QCoreApplication::translate("AntonovClass", "Work offset - G54 ... G57 [*]", nullptr));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget_2->horizontalHeaderItem(0);
        ___qtablewidgetitem44->setText(QCoreApplication::translate("AntonovClass", "\320\235\320\260\320\267\320\262\320\260\320\275\320\270\320\265", nullptr));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget_2->horizontalHeaderItem(1);
        ___qtablewidgetitem45->setText(QCoreApplication::translate("AntonovClass", "\320\224\320\273\320\270\320\275\320\260 X", nullptr));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget_2->horizontalHeaderItem(2);
        ___qtablewidgetitem46->setText(QCoreApplication::translate("AntonovClass", "\320\224\320\273\320\270\320\275\320\260 Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget_2->horizontalHeaderItem(3);
        ___qtablewidgetitem47->setText(QCoreApplication::translate("AntonovClass", "\320\240\320\260\320\264\320\270\321\203\321\201", nullptr));

        const bool __sortingEnabled1 = tableWidget_2->isSortingEnabled();
        tableWidget_2->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget_2->item(0, 1);
        ___qtablewidgetitem48->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget_2->item(0, 2);
        ___qtablewidgetitem49->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget_2->item(1, 1);
        ___qtablewidgetitem50->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget_2->item(1, 2);
        ___qtablewidgetitem51->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget_2->item(2, 1);
        ___qtablewidgetitem52->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget_2->item(2, 2);
        ___qtablewidgetitem53->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget_2->item(3, 1);
        ___qtablewidgetitem54->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget_2->item(3, 2);
        ___qtablewidgetitem55->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget_2->item(4, 1);
        ___qtablewidgetitem56->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget_2->item(4, 2);
        ___qtablewidgetitem57->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget_2->item(5, 1);
        ___qtablewidgetitem58->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget_2->item(5, 2);
        ___qtablewidgetitem59->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget_2->item(6, 1);
        ___qtablewidgetitem60->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget_2->item(6, 2);
        ___qtablewidgetitem61->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget_2->item(7, 1);
        ___qtablewidgetitem62->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget_2->item(7, 2);
        ___qtablewidgetitem63->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget_2->item(8, 1);
        ___qtablewidgetitem64->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget_2->item(8, 2);
        ___qtablewidgetitem65->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget_2->item(9, 1);
        ___qtablewidgetitem66->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget_2->item(9, 2);
        ___qtablewidgetitem67->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget_2->item(10, 1);
        ___qtablewidgetitem68->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget_2->item(10, 2);
        ___qtablewidgetitem69->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget_2->item(11, 1);
        ___qtablewidgetitem70->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget_2->item(11, 2);
        ___qtablewidgetitem71->setText(QCoreApplication::translate("AntonovClass", "0.000", nullptr));
        tableWidget_2->setSortingEnabled(__sortingEnabled1);

        lineEdit_69->setText(QCoreApplication::translate("AntonovClass", "Offset", nullptr));
        button_podtverkorrert->setText(QCoreApplication::translate("AntonovClass", "\320\237\320\276\320\264\321\202\320\262\320\265\321\200\320\264\320\270\321\202\321\214", nullptr));
        button_otmenakorrert->setText(QCoreApplication::translate("AntonovClass", "\320\236\321\202\320\274\320\265\320\275\320\260", nullptr));
        button_null1_3->setText(QString());
        button_null1_4->setText(QString());
        button_korrekt->setText(QCoreApplication::translate("AntonovClass", "Work \n"
"offset", nullptr));
        button_null1_6->setText(QString());
        button_null1_7->setText(QString());
        button_backk2->setText(QCoreApplication::translate("AntonovClass", "\320\222\320\276\320\267\320\262\321\200\320\260\321\202", nullptr));
        button_null1_9->setText(QString());
        button_downwiget2->setText(QCoreApplication::translate("AntonovClass", "\320\222\320\275\320\270\320\267", nullptr));
        button_leftwiget2->setText(QCoreApplication::translate("AntonovClass", "\320\222\320\273\320\265\320\262\320\276", nullptr));
        button_wiborwiget2->setText(QCoreApplication::translate("AntonovClass", "\320\222\321\213\320\261\320\276\321\200", nullptr));
        button_rightwiget2->setText(QCoreApplication::translate("AntonovClass", "\320\222\320\277\321\200\320\260\320\262\320\276", nullptr));
        button_upwiget2->setText(QCoreApplication::translate("AntonovClass", "\320\222\320\262\320\265\321\200\321\205", nullptr));
        button_null1_15->setText(QString());
        label_time_2->setText(QCoreApplication::translate("AntonovClass", "label_time", nullptr));
        label_date_2->setText(QCoreApplication::translate("AntonovClass", "label_date", nullptr));
    } // retranslateUi

};

namespace Ui {
    class AntonovClass: public Ui_AntonovClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ANTONOV_H
